### ISSUE TITLE
Icons/Switches are not properly scaled

### ISSUE THREAD

**Issue by zzzardoz** [HarlemSquirrel/gnome-shell-extension-sensory-perception#10]
**Describe the bug**
Since Gnome 3.32 icons and switches are way to big. (Please see screenshots.) I'm on latest Arch and I have a 4K screen with 200% scale. 

**Screenshots**
![extension](https://user-images.githubusercontent.com/7443696/56244251-c7841e80-609c-11e9-9393-0d8c76186d7a.png)
![settings](https://user-images.githubusercontent.com/7443696/56244264-cbb03c00-609c-11e9-8e68-b647ee989ee0.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by HarlemSquirrel** [comment]
Hi @zzzardoz , what version of the extension are you using? Can you try the master branch? 
Thanks!

**Comment by zzzardoz** [comment]
@HarlemSquirrel: Just tried master branch, but it makes no difference. I was using the latest version from Gnome Extensions website.

Thanks for the fast response! :-)

**Comment by HarlemSquirrel** [comment]
Does changing scaling to 100% make a difference?

**Comment by zzzardoz** [comment]
Unfortunately not, still the same...

Edit: I just tried with my notebook (FullHD/no scaling) which is also on latest Arch: Same strange scaling again.

**Comment by ellperro** [comment]
same here, ubuntu 19.04 gnome 3.32.0 monitor 1920x1200 (dual monitor setup) no scaling
Big icons -> doesn't fit the screen

Screenshot:
![Schermafdruk_sensory_perception](https://user-images.githubusercontent.com/49925114/56618750-053ff480-6613-11e9-8a09-0305d71bceda.png)

**Comment by HarlemSquirrel** [comment]
I think a0acd43540167ebe2dace2db984ed7670aa336b9 should fix this. Could someone please try the latest code from master and let me know?

**Comment by zzzardoz** [comment]
@HarlemSquirrel: That indeed fixes the icons. But I'd suggest for going with 16px. Switches in prefs are still too large.

**Comment by HarlemSquirrel** [comment]
I've released a new version which includes the menu icon size reduction. It looks like the stretched switches in the preferences menu is related to how the grid is used. Haven't found a way to fix it yet.

**Comment by HarlemSquirrel** [comment]
This should be fixed
