### ISSUE TITLE
The icon is too big.

### ISSUE THREAD

**Issue by laichiaheng** [HarlemSquirrel/gnome-shell-extension-sensory-perception#11]
**Describe the bug**
Icon is too big, and the list is out of range of my screen

**To Reproduce**
1. Click on 'the indicator'

**Expected behavior**
I can scroll down the menu
**Screenshots**
![2019-05-03 15-45-21 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/57125055-7cffe300-6dba-11e9-9966-19d4234978eb.png)

**Desktop (please complete the following information):**
 - OS: [Manjaro]

**Comment by HarlemSquirrel** [comment]
This should be fixed now in v10

**Comment by laichiaheng** [comment]
Yes, it is solved. Thank you.
