### ISSUE TITLE
Settings are not working in GNOME Shell 3.32.1

### ISSUE THREAD

**Issue by rovellipaolo** [HarlemSquirrel/gnome-shell-extension-sensory-perception#14]
**Describe the bug**
When opening the settings, an error is displayed.

**To Reproduce**
1. Go to https://extensions.gnome.org/local/
2. Click on 'Configure this extension' button
3. An error is displayed

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - GNOME Shell: 3.32.1

**Additional context**
```
GLib.ShellError: Text was empty (or contained only whitespace)

Stack trace:
  _getSensorsLabels@/home/provelli/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:195:29
  _init@/home/provelli/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:143:5
  buildPrefsWidget@/home/provelli/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:276:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
  main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
  @<main>:1:43
 ```

**Comment by atanaschristov** [comment]
I'm having the same issue:

![image](https://user-images.githubusercontent.com/5697100/59778926-082c2e00-92c0-11e9-803b-05bf51efcc39.png)

**Comment by HarlemSquirrel** [comment]
What version of the extension are you running? Have you tried manually deleting the extension and then installing again?

To manually delete the extension you can run the command below, log out, and then log back in. 

```
rm -r ~/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io
```

**Comment by rovellipaolo** [comment]
I was running version _10_ (the latest one available here: https://extensions.gnome.org/extension/1145/sensory-perception/).

But, yes, manually deleting the extension actually fixed the issue.
Although now, instead of seeing the setting of your extension, I see the general GNOME Shell setting page.
