### ISSUE TITLE
Something's gone wrong (Not working on Ubuntu 19.04)

### ISSUE THREAD

**Issue by cassv24** [HarlemSquirrel/gnome-shell-extension-sensory-perception#16]
**Describe the bug**
When I click the settings in the menu I get the following error:

`The settings of extension sensory-perception@HarlemSquirrel.github.io had an error:
```
GLib.ShellError: Text was empty (or contained only whitespace)
```

Stack trace:
```
_getSensorsLabels@~/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:195:29
_init@~/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:143:5
buildPrefsWidget@~/.local/share/gnome-shell/extensions/sensory-perception@HarlemSquirrel.github.io/prefs.js:276:18
_selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:75:22
_onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:320:17
main@resource:///org/gnome/shell/extensionPrefs/main.js:635:5
@<main>:1:43
```
`

**To Reproduce**
1. Go to the menu
2. Click on settings
3. See error

**Expected behavior**
To open the settings panel

**Screenshots**
![Screenshot from 2019-07-08 12-55-10](https://user-images.githubusercontent.com/23457150/60828229-ea940b00-a17f-11e9-9441-61456828a3f3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 19.04

**Comment by HarlemSquirrel** [comment]
Hi @cassv24 , could you share the output of `sensors`?

**Comment by cassv24** [comment]
I'm not sure what are you asking for, but this is the output of the program:

![Screenshot from 2019-07-14 18-38-57](https://user-images.githubusercontent.com/23457150/61190204-b8464a00-a666-11e9-85d5-567ce99e1db4.png)

**Comment by HarlemSquirrel** [comment]
@cassv24 I'm looking for the output of running the command `sensors` in a terminal. 

It should look something like this:

```
➤  sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +56.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +48.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +50.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +50.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +56.0°C  (high = +100.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +56.0°C  (crit = +120.0°C)

iwlwifi-virtual-0
Adapter: Virtual device
temp1:        +29.0°C  

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +44.5°C
```

**Comment by cassv24** [comment]
Hi, sorry for the delay.

after installing `lm-sensors` it's working now. 

You should add _lm-sensors_ as an explicit dependency in your **README.md**, as part of the installation instructions.

**Comment by HarlemSquirrel** [comment]
I'm glad that worked! I just updated the README. Thanks for the suggestion :)
