### ISSUE TITLE
Translation in UI not shown

### ISSUE THREAD

**Issue by Etamuk** [HarlemSquirrel/gnome-shell-extension-sensory-perception#17]
**Describe the bug**
I am using my computer with german interface. After installing this extension the UI is still in english. The translation file de.po is availible in the extension folder.

**To Reproduce**
1. You need a system language which is not english, f.e. german
2. Install this ext.
3. After relogin or Alt+F2 + r the UI of this ext. is still english

**Expected behavior**
See this ext. with german interface
**Screenshots**
---

**Desktop (please complete the following information):**
 - Ubuntu 19.04
 - Gnome 3.32.1

**Comment by jose1711** [comment]
@Etamuk please test with https://github.com/jose1711/gnome-shell-extension-sensory-perception/commit/62c59897b6d6035fbefeb2fd794dc82cb3ed6674

**Comment by HarlemSquirrel** [comment]
It's this still broken in latest v16?

**Comment by jose1711** [comment]
Tested this on a fresh v16 installed via extensions.gnome.org. Same problem, all is in English. Placing the `.mo` and `.po` files into `locale/LANG/sk/LC_MESSAGES` and minor changes in `prefs.js` as done in test branch still work.

**Comment by Etamuk** [comment]
I installed the latest V16 from https://extensions.gnome.org. Still the whole UI in English.

**Comment by HarlemSquirrel** [comment]
@jose1711 could you open a pull request with those changes?

**Comment by jose1711** [comment]
PR raised. Feel free to comment and/or edit directly.
