### ISSUE TITLE
Sensor no longer visible in panel (always N/A)

### ISSUE THREAD

**Issue by jose1711** [HarlemSquirrel/gnome-shell-extension-sensory-perception#20]
I can no longer can see a sensor value in panel. Might've been caused by upgrading to Gnome 3.34.

**Comment by HarlemSquirrel** [comment]
@jose1711 d72ab9eec9082e1d8758fba41d884a1d690ccf3d should fix this. Please test out the master branch if you can.

**Comment by jose1711** [comment]
Thank you for the fix, closing
