### ISSUE TITLE
Gnome 41 support?

### ISSUE THREAD

**Issue by Netherquark** [HarlemSquirrel/gnome-shell-extension-sensory-perception#43]
This extension was working perfectly with Fedora 34/Gnome 40 but its not supported on Fedora 35/Gnome 41. Hope the dev can take the time to update it :)

**Comment by nlincke** [comment]
Upvote! I would also love to see an update to solve this issue...

**Comment by VergeDX** [comment]
`sed -i 's/"40"/"40", "41"/g' metadata.json` works for me fine : )

**Comment by Netherquark** [comment]
> `sed -i 's/"40"/"40", "41"/g' metadata.json` works for me fine : )

This means its forward-compatible? thats great! So the dev would just need to publish a new release with this change right? @HarlemSquirrel

**Comment by HarlemSquirrel** [comment]
Published [v15](https://github.com/HarlemSquirrel/gnome-shell-extension-sensory-perception/releases/tag/v15) and submitted for review

**Comment by HarlemSquirrel** [comment]
Had to make some more changes from review on v15 but now v16 is live.
