### ISSUE TITLE
Settings Not Working on v7 (Gnome 3.32, gjs 1.56.0)

### ISSUE THREAD

**Issue by saildata** [HarlemSquirrel/gnome-shell-extension-sensory-perception#8]
Sorry, I should have opened a new bug request, so that it doesn't get burried. See #7.

**Comment by HarlemSquirrel** [comment]
Yeah, I've been trying to get it working. 

https://gitlab.gnome.org/GNOME/gjs/issues/234

If you have any ideas, let me know!

**Comment by HarlemSquirrel** [comment]
Should be working now in the `master` branch as of aa09ab0ac44a8ca67df164ac9744a7c55a406f97

**Comment by HarlemSquirrel** [comment]
I'm going to close this now since it should be resolved.
